'use client'

import { motion } from 'framer-motion'
import Navbar from '@/components/Navbar'
import { useLanguage } from '@/contexts/LanguageContext'
import { 
  Brain, 
  Activity, 
  Zap, 
  Target,
  AlertTriangle,
  CheckCircle,
  BarChart3,
  Layers,
  Sparkles,
  Eye,
  FileText,
  Shield,
  Info
} from 'lucide-react'

export default function MethodologyPage() {
  const { language, isRTL } = useLanguage()

  const content = {
    en: {
      title: 'How It',
      titleHighlight: 'Works',
      subtitle: 'Understanding our AI detection methodology',
      intro: 'Human Verified Hub uses advanced linguistic analysis and machine learning to determine the likelihood that content was written by a human or generated by AI. Our approach is probabilistic, meaning we provide confidence scores rather than absolute verdicts.',
      
      metricsTitle: 'Key Metrics We Analyze',
      metrics: [
        {
          icon: Brain,
          title: 'Perplexity',
          description: 'Perplexity measures how "surprised" a language model would be by the text. Human writing typically has higher perplexity due to creative word choices and unexpected phrasing. AI-generated text tends to be more predictable with lower perplexity.',
          high: 'High perplexity suggests human writing',
          low: 'Low perplexity may indicate AI generation'
        },
        {
          icon: Activity,
          title: 'Burstiness',
          description: 'Burstiness measures variation in sentence length and complexity. Humans naturally write with varied rhythm - mixing short, punchy sentences with longer, complex ones. AI tends to maintain more consistent sentence structures.',
          high: 'High burstiness suggests human writing',
          low: 'Low burstiness may indicate AI generation'
        },
        {
          icon: Layers,
          title: 'Lexical Richness',
          description: 'This analyzes vocabulary diversity, including unique word usage, rare words, and the ratio of unique words to total words. Humans often use more varied and context-specific vocabulary.',
          high: 'Rich vocabulary suggests human authorship',
          low: 'Repetitive vocabulary may indicate AI'
        },
        {
          icon: BarChart3,
          title: 'Syntax Analysis',
          description: 'We examine sentence structure patterns, including clause complexity, punctuation usage, and grammatical variety. Human writing shows more structural diversity and occasional "imperfections" that feel natural.',
          high: 'Varied syntax suggests human writing',
          low: 'Uniform patterns may indicate AI'
        }
      ],

      processTitle: 'Our Analysis Process',
      processSteps: [
        {
          step: 1,
          title: 'Text Preprocessing',
          description: 'We clean and normalize the input text, removing formatting artifacts while preserving meaningful linguistic features.'
        },
        {
          step: 2,
          title: 'Multi-dimensional Analysis',
          description: 'Our AI engine (powered by Gemini) analyzes the text across multiple linguistic dimensions simultaneously.'
        },
        {
          step: 3,
          title: 'Pattern Recognition',
          description: 'We identify patterns characteristic of AI-generated text, including common AI "fingerprints" and writing styles.'
        },
        {
          step: 4,
          title: 'Score Calculation',
          description: 'All metrics are weighted and combined to produce a human probability score from 0% to 100%.'
        }
      ],

      limitationsTitle: 'Important Limitations',
      limitations: [
        {
          title: 'No Detection is 100% Accurate',
          description: 'AI detection technology is inherently probabilistic. False positives (human content flagged as AI) and false negatives (AI content flagged as human) can and do occur.'
        },
        {
          title: 'AI Technology Evolves Rapidly',
          description: 'As AI models improve, detection becomes more challenging. We continuously update our algorithms, but there may be lag periods.'
        },
        {
          title: 'Short Texts Are Less Reliable',
          description: 'Accuracy increases with text length. Very short passages may not provide enough patterns for reliable analysis.'
        },
        {
          title: 'Editing Can Affect Results',
          description: 'Heavily edited AI text or AI-assisted human writing creates hybrid patterns that are difficult to classify definitively.'
        },
        {
          title: 'Language & Domain Variations',
          description: 'Detection accuracy may vary across languages, technical domains, and writing styles. Our primary optimization is for English text.'
        }
      ],

      scoresTitle: 'Understanding Score Ranges',
      scores: [
        { range: '0-30%', label: 'AI Confirmed', description: 'Strong indicators of AI generation. Multiple AI fingerprints detected.', color: 'red' },
        { range: '31-60%', label: 'Hybrid/Uncertain', description: 'Mixed signals. Could be AI-assisted writing or heavily edited AI content.', color: 'yellow' },
        { range: '61-100%', label: 'Human Original', description: 'Strong indicators of human authorship. Natural linguistic patterns present.', color: 'green' }
      ],

      disclaimerTitle: 'Usage Disclaimer',
      disclaimer: 'This tool is for educational and research purposes. Results are indicative and should not be the sole basis for academic or legal decisions. Always use multiple verification methods and human judgment alongside automated tools.',

      imageTitle: 'Image Detection Methodology',
      imageIntro: 'For AI-generated image detection, we analyze visual artifacts and patterns unique to AI image generation:',
      imageMetrics: [
        { title: 'Anatomical Analysis', description: 'Examining hands, eyes, teeth, and other body parts for AI-typical anomalies' },
        { title: 'Texture Analysis', description: 'Checking for unnatural skin textures, hair rendering, and fabric patterns' },
        { title: 'Physics & Lighting', description: 'Verifying shadow consistency, reflection accuracy, and perspective logic' },
        { title: 'AI Fingerprints', description: 'Detecting repetitive patterns, edge artifacts, and micro-level inconsistencies' }
      ]
    },
    ar: {
      title: 'كيف',
      titleHighlight: 'يعمل',
      subtitle: 'فهم منهجية كشف الذكاء الاصطناعي',
      intro: 'يستخدم Human Verified Hub تحليلاً لغوياً متقدماً وتعلماً آلياً لتحديد احتمالية أن يكون المحتوى مكتوباً بواسطة إنسان أو مولداً بالذكاء الاصطناعي. نهجنا احتمالي، مما يعني أننا نقدم درجات ثقة بدلاً من أحكام مطلقة.',
      
      metricsTitle: 'المقاييس الرئيسية التي نحللها',
      metrics: [
        {
          icon: Brain,
          title: 'الحيرة (Perplexity)',
          description: 'تقيس الحيرة مدى "مفاجأة" نموذج اللغة بالنص. الكتابة البشرية عادة لديها حيرة أعلى بسبب اختيارات الكلمات الإبداعية والصياغة غير المتوقعة. النص المولد بالذكاء الاصطناعي يميل لأن يكون أكثر قابلية للتنبؤ بحيرة أقل.',
          high: 'الحيرة العالية تشير للكتابة البشرية',
          low: 'الحيرة المنخفضة قد تشير للتوليد الآلي'
        },
        {
          icon: Activity,
          title: 'الانفجارية (Burstiness)',
          description: 'تقيس الانفجارية التباين في طول الجمل وتعقيدها. البشر يكتبون بشكل طبيعي بإيقاع متنوع - يمزجون الجمل القصيرة المؤثرة مع الجمل الأطول والأكثر تعقيداً. الذكاء الاصطناعي يميل للحفاظ على هياكل جمل أكثر اتساقاً.',
          high: 'الانفجارية العالية تشير للكتابة البشرية',
          low: 'الانفجارية المنخفضة قد تشير للتوليد الآلي'
        },
        {
          icon: Layers,
          title: 'الثراء اللغوي',
          description: 'يحلل هذا تنوع المفردات، بما في ذلك استخدام الكلمات الفريدة والكلمات النادرة ونسبة الكلمات الفريدة إلى إجمالي الكلمات. البشر غالباً يستخدمون مفردات أكثر تنوعاً وخصوصية للسياق.',
          high: 'المفردات الغنية تشير للتأليف البشري',
          low: 'المفردات المتكررة قد تشير للذكاء الاصطناعي'
        },
        {
          icon: BarChart3,
          title: 'تحليل البناء',
          description: 'نفحص أنماط بنية الجملة، بما في ذلك تعقيد الجمل واستخدام علامات الترقيم والتنوع النحوي. الكتابة البشرية تظهر تنوعاً بنيوياً أكثر و"عيوباً" عرضية تبدو طبيعية.',
          high: 'البناء المتنوع يشير للكتابة البشرية',
          low: 'الأنماط الموحدة قد تشير للذكاء الاصطناعي'
        }
      ],

      processTitle: 'عملية التحليل',
      processSteps: [
        {
          step: 1,
          title: 'معالجة النص',
          description: 'ننظف ونعالج النص المدخل، مع إزالة artifacts التنسيق مع الحفاظ على الخصائص اللغوية ذات المعنى.'
        },
        {
          step: 2,
          title: 'تحليل متعدد الأبعاد',
          description: 'محرك الذكاء الاصطناعي (المدعوم بـ Gemini) يحلل النص عبر أبعاد لغوية متعددة في وقت واحد.'
        },
        {
          step: 3,
          title: 'التعرف على الأنماط',
          description: 'نحدد الأنماط المميزة للنص المولد بالذكاء الاصطناعي، بما في ذلك "بصمات" AI الشائعة وأساليب الكتابة.'
        },
        {
          step: 4,
          title: 'حساب النتيجة',
          description: 'يتم ترجيح جميع المقاييس ودمجها لإنتاج درجة احتمالية بشرية من 0% إلى 100%.'
        }
      ],

      limitationsTitle: 'قيود مهمة',
      limitations: [
        {
          title: 'لا يوجد كشف دقيق 100%',
          description: 'تقنية كشف الذكاء الاصطناعي احتمالية بطبيعتها. الإيجابيات الكاذبة والسلبيات الكاذبة يمكن أن تحدث.'
        },
        {
          title: 'تقنية AI تتطور بسرعة',
          description: 'مع تحسن نماذج AI، يصبح الكشف أكثر صعوبة. نحدث خوارزمياتنا باستمرار، لكن قد تكون هناك فترات تأخير.'
        },
        {
          title: 'النصوص القصيرة أقل موثوقية',
          description: 'تزداد الدقة مع طول النص. الفقرات القصيرة جداً قد لا توفر أنماطاً كافية للتحليل الموثوق.'
        },
        {
          title: 'التحرير يؤثر على النتائج',
          description: 'نص AI المحرر بشكل كبير أو الكتابة البشرية بمساعدة AI تخلق أنماطاً هجينة يصعب تصنيفها بشكل قاطع.'
        },
        {
          title: 'اختلافات اللغة والمجال',
          description: 'قد تختلف دقة الكشف عبر اللغات والمجالات التقنية وأساليب الكتابة. تحسيننا الأساسي للنص الإنجليزي.'
        }
      ],

      scoresTitle: 'فهم نطاقات النتائج',
      scores: [
        { range: '0-30%', label: 'AI مؤكد', description: 'مؤشرات قوية على التوليد الآلي. تم اكتشاف بصمات AI متعددة.', color: 'red' },
        { range: '31-60%', label: 'هجين/غير مؤكد', description: 'إشارات مختلطة. قد يكون كتابة بمساعدة AI أو محتوى AI محرر بشكل كبير.', color: 'yellow' },
        { range: '61-100%', label: 'بشري أصيل', description: 'مؤشرات قوية على التأليف البشري. أنماط لغوية طبيعية موجودة.', color: 'green' }
      ],

      disclaimerTitle: 'إخلاء المسؤولية',
      disclaimer: 'هذه الأداة للأغراض التعليمية والبحثية. النتائج إرشادية ولا يجب أن تكون الأساس الوحيد للقرارات الأكاديمية أو القانونية. استخدم دائماً طرق تحقق متعددة وحكم بشري إلى جانب الأدوات الآلية.',

      imageTitle: 'منهجية كشف الصور',
      imageIntro: 'لكشف الصور المولدة بالذكاء الاصطناعي، نحلل التشوهات البصرية والأنماط الفريدة لتوليد صور AI:',
      imageMetrics: [
        { title: 'التحليل التشريحي', description: 'فحص الأيدي والعيون والأسنان وأجزاء الجسم الأخرى للتشوهات النموذجية لـ AI' },
        { title: 'تحليل الأنسجة', description: 'التحقق من القوام غير الطبيعي للجلد وعرض الشعر وأنماط القماش' },
        { title: 'الفيزياء والإضاءة', description: 'التحقق من اتساق الظلال ودقة الانعكاس ومنطق المنظور' },
        { title: 'بصمات AI', description: 'اكتشاف الأنماط المتكررة وتشوهات الحواف والتناقضات على المستوى الدقيق' }
      ]
    }
  }

  const t = language === 'ar' ? content.ar : content.en

  return (
    <div className="min-h-screen bg-black cyber-grid" dir={isRTL ? 'rtl' : 'ltr'}>
      <Navbar />

      <main className="max-w-5xl mx-auto px-4 py-8 pt-24">
        {/* Hero */}
        <div className="text-center mb-12">
          <motion.h1
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            className="text-4xl md:text-5xl font-bold text-white mb-4"
          >
            {t.title}{' '}
            <span className="text-gradient neon-text-glow">{t.titleHighlight}</span>
          </motion.h1>
          <motion.p
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
            className="text-gray-400 text-lg max-w-2xl mx-auto"
          >
            {t.subtitle}
          </motion.p>
        </div>

        {/* Introduction */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2 }}
          className="glass-card p-8 mb-12"
        >
          <div className="flex items-start gap-4">
            <div className="w-12 h-12 rounded-xl bg-purple-900/30 flex items-center justify-center flex-shrink-0">
              <Info className="w-6 h-6 text-purple-400" />
            </div>
            <p className="text-gray-300 leading-relaxed">{t.intro}</p>
          </div>
        </motion.div>

        {/* Key Metrics */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.3 }}
          className="mb-12"
        >
          <h2 className="text-2xl font-bold text-white mb-8 flex items-center gap-3">
            <BarChart3 className="w-6 h-6 text-purple-400" />
            {t.metricsTitle}
          </h2>
          
          <div className="grid md:grid-cols-2 gap-6">
            {t.metrics.map((metric, i) => {
              const Icon = metric.icon
              return (
                <div key={i} className="glass-card p-6">
                  <div className="flex items-center gap-3 mb-4">
                    <div className="w-10 h-10 rounded-xl bg-purple-900/30 flex items-center justify-center">
                      <Icon className="w-5 h-5 text-purple-400" />
                    </div>
                    <h3 className="text-lg font-semibold text-white">{metric.title}</h3>
                  </div>
                  <p className="text-gray-400 text-sm mb-4 leading-relaxed">{metric.description}</p>
                  <div className="space-y-2">
                    <div className="flex items-center gap-2 text-green-400 text-xs">
                      <CheckCircle className="w-3 h-3" />
                      {metric.high}
                    </div>
                    <div className="flex items-center gap-2 text-red-400 text-xs">
                      <AlertTriangle className="w-3 h-3" />
                      {metric.low}
                    </div>
                  </div>
                </div>
              )
            })}
          </div>
        </motion.div>

        {/* Process Steps */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.4 }}
          className="mb-12"
        >
          <h2 className="text-2xl font-bold text-white mb-8 flex items-center gap-3">
            <Zap className="w-6 h-6 text-purple-400" />
            {t.processTitle}
          </h2>
          
          <div className="space-y-4">
            {t.processSteps.map((step, i) => (
              <div key={i} className="glass-card p-6 flex items-start gap-4">
                <div className="w-10 h-10 rounded-full bg-purple-600/20 border border-purple-500/30 flex items-center justify-center flex-shrink-0">
                  <span className="text-purple-400 font-bold">{step.step}</span>
                </div>
                <div>
                  <h3 className="text-white font-semibold mb-1">{step.title}</h3>
                  <p className="text-gray-400 text-sm">{step.description}</p>
                </div>
              </div>
            ))}
          </div>
        </motion.div>

        {/* Score Ranges */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.5 }}
          className="mb-12"
        >
          <h2 className="text-2xl font-bold text-white mb-8 flex items-center gap-3">
            <Target className="w-6 h-6 text-purple-400" />
            {t.scoresTitle}
          </h2>
          
          <div className="grid md:grid-cols-3 gap-4">
            {t.scores.map((score, i) => (
              <div 
                key={i} 
                className={`p-6 rounded-xl border ${
                  score.color === 'red' ? 'bg-red-900/10 border-red-500/30' :
                  score.color === 'yellow' ? 'bg-yellow-900/10 border-yellow-500/30' :
                  'bg-green-900/10 border-green-500/30'
                }`}
              >
                <div className={`text-2xl font-bold mb-2 ${
                  score.color === 'red' ? 'text-red-400' :
                  score.color === 'yellow' ? 'text-yellow-400' :
                  'text-green-400'
                }`}>
                  {score.range}
                </div>
                <div className="text-white font-semibold mb-2">{score.label}</div>
                <p className="text-gray-400 text-sm">{score.description}</p>
              </div>
            ))}
          </div>
        </motion.div>

        {/* Limitations */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.6 }}
          className="mb-12"
        >
          <h2 className="text-2xl font-bold text-white mb-8 flex items-center gap-3">
            <AlertTriangle className="w-6 h-6 text-yellow-400" />
            {t.limitationsTitle}
          </h2>
          
          <div className="glass-card p-6">
            <div className="space-y-4">
              {t.limitations.map((limitation, i) => (
                <div key={i} className="pb-4 border-b border-purple-900/20 last:border-0 last:pb-0">
                  <h3 className="text-yellow-400 font-semibold mb-1">{limitation.title}</h3>
                  <p className="text-gray-400 text-sm">{limitation.description}</p>
                </div>
              ))}
            </div>
          </div>
        </motion.div>

        {/* Image Detection */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.7 }}
          className="mb-12"
        >
          <h2 className="text-2xl font-bold text-white mb-8 flex items-center gap-3">
            <Eye className="w-6 h-6 text-purple-400" />
            {t.imageTitle}
          </h2>
          
          <div className="glass-card p-6">
            <p className="text-gray-400 mb-6">{t.imageIntro}</p>
            <div className="grid sm:grid-cols-2 gap-4">
              {t.imageMetrics.map((metric, i) => (
                <div key={i} className="p-4 bg-black/30 rounded-xl border border-purple-900/20">
                  <h3 className="text-white font-semibold mb-2">{metric.title}</h3>
                  <p className="text-gray-400 text-sm">{metric.description}</p>
                </div>
              ))}
            </div>
          </div>
        </motion.div>

        {/* Disclaimer */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.8 }}
          className="mb-12"
        >
          <div className="p-6 bg-yellow-900/10 border border-yellow-500/30 rounded-xl">
            <div className="flex items-start gap-4">
              <Shield className="w-6 h-6 text-yellow-400 flex-shrink-0 mt-1" />
              <div>
                <h3 className="text-yellow-400 font-semibold mb-2">{t.disclaimerTitle}</h3>
                <p className="text-gray-300 text-sm leading-relaxed">{t.disclaimer}</p>
              </div>
            </div>
          </div>
        </motion.div>
      </main>

      {/* Footer */}
      <footer className="border-t border-purple-900/30">
        <div className="max-w-5xl mx-auto px-4 py-6 text-center">
          <p className="text-gray-500 text-xs">© 2026 Human Verified Hub. All rights reserved.</p>
        </div>
      </footer>
    </div>
  )
}
