'use client'

import { useState } from 'react'
import { motion } from 'framer-motion'
import { jsPDF } from 'jspdf'
import QRCode from 'qrcode'
import { Award, Download, Loader2, ExternalLink } from 'lucide-react'

interface CertificateGeneratorProps {
  score: number
  content: string
  verificationId: string | null
  userId?: string
}

export default function CertificateGenerator({
  score,
  content,
  verificationId,
  userId,
}: CertificateGeneratorProps) {
  const [generating, setGenerating] = useState(false)
  const [certificateId, setCertificateId] = useState<string | null>(null)

  const generateCertificate = async () => {
    setGenerating(true)

    try {
      // First, create certificate record in database
      const response = await fetch('/api/certificate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          verificationId,
          score,
          content: content.substring(0, 200),
          userId,
        }),
      })

      const data = await response.json()
      
      if (data.error) {
        console.error('Certificate error:', data.error)
        return
      }

      setCertificateId(data.certificateId)

      // Generate QR code
      const verifyUrl = `${window.location.origin}/verify/${data.certificateId}`
      const qrDataUrl = await QRCode.toDataURL(verifyUrl, {
        width: 150,
        margin: 1,
        color: {
          dark: '#1e293b',
          light: '#f8fafc',
        },
      })

      // Create PDF
      const pdf = new jsPDF({
        orientation: 'landscape',
        unit: 'mm',
        format: 'a4',
      })

      const width = pdf.internal.pageSize.getWidth()
      const height = pdf.internal.pageSize.getHeight()

      // Background - Black
      pdf.setFillColor(0, 0, 0)
      pdf.rect(0, 0, width, height, 'F')

      // Purple gradient border effect
      pdf.setDrawColor(168, 85, 247)
      pdf.setLineWidth(2)
      pdf.rect(10, 10, width - 20, height - 20)

      // Inner border
      pdf.setDrawColor(139, 92, 246)
      pdf.setLineWidth(0.5)
      pdf.rect(15, 15, width - 30, height - 30)

      // Corner decorations with purple
      const corners = [
        { x: 20, y: 20 },
        { x: width - 20, y: 20 },
        { x: 20, y: height - 20 },
        { x: width - 20, y: height - 20 },
      ]

      pdf.setFillColor(168, 85, 247)
      corners.forEach(({ x, y }) => {
        pdf.circle(x, y, 3, 'F')
      })

      // Title
      pdf.setTextColor(168, 85, 247)
      pdf.setFontSize(36)
      pdf.setFont('helvetica', 'bold')
      pdf.text('CERTIFICATE OF AUTHENTICITY', width / 2, 45, { align: 'center' })

      // Subtitle
      pdf.setTextColor(139, 92, 246)
      pdf.setFontSize(14)
      pdf.setFont('helvetica', 'normal')
      pdf.text('Human-Verified Hub | Forensic Linguistic Analysis', width / 2, 55, { align: 'center' })

      // Main text
      pdf.setTextColor(248, 250, 252)
      pdf.setFontSize(16)
      pdf.text('This certifies that the analyzed content has been verified as', width / 2, 75, { align: 'center' })

      // Human Original badge
      pdf.setFontSize(28)
      pdf.setTextColor(16, 185, 129)
      pdf.setFont('helvetica', 'bold')
      pdf.text('HUMAN ORIGINAL', width / 2, 95, { align: 'center' })

      // Score display
      pdf.setFontSize(48)
      pdf.setTextColor(16, 185, 129)
      pdf.text(`${score}%`, width / 2, 120, { align: 'center' })

      pdf.setFontSize(12)
      pdf.setTextColor(148, 163, 184)
      pdf.text('Human Authenticity Score', width / 2, 130, { align: 'center' })

      // Certificate details
      const detailsY = 145
      pdf.setFontSize(10)
      pdf.setTextColor(148, 163, 184)
      
      pdf.text(`Certificate ID: ${data.certificateId}`, 30, detailsY)
      pdf.text(`Issued: ${new Date().toLocaleDateString('en-US', { 
        year: 'numeric', 
        month: 'long', 
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit'
      })}`, 30, detailsY + 8)

      // Content preview
      pdf.setFontSize(9)
      pdf.text('Content Preview:', 30, detailsY + 20)
      const preview = content.substring(0, 150).replace(/\n/g, ' ') + '...'
      const splitPreview = pdf.splitTextToSize(preview, 150)
      pdf.text(splitPreview, 30, detailsY + 28)

      // Add QR code
      pdf.addImage(qrDataUrl, 'PNG', width - 55, detailsY - 10, 35, 35)
      pdf.setFontSize(8)
      pdf.text('Scan to verify', width - 38, detailsY + 28, { align: 'center' })

      // Seal
      pdf.setDrawColor(168, 85, 247)
      pdf.setLineWidth(1)
      pdf.circle(width / 2, height - 35, 15)
      pdf.setTextColor(168, 85, 247)
      pdf.setFontSize(8)
      pdf.text('VERIFIED', width / 2, height - 35, { align: 'center' })

      // Footer
      pdf.setTextColor(100, 116, 139)
      pdf.setFontSize(8)
      pdf.text('This certificate was generated by Human-Verified Hub using advanced AI detection algorithms.', width / 2, height - 15, { align: 'center' })
      pdf.text('Verify authenticity at: ' + verifyUrl, width / 2, height - 10, { align: 'center' })

      // Save PDF
      pdf.save(`human-verified-certificate-${data.certificateId}.pdf`)

    } catch (error) {
      console.error('Failed to generate certificate:', error)
    } finally {
      setGenerating(false)
    }
  }

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="bg-gradient-to-r from-purple-900/20 to-green-900/20 rounded-xl p-6 border border-purple-500/30"
    >
      <div className="flex flex-col sm:flex-row items-start sm:items-center gap-4">
        <div className="w-16 h-16 rounded-full bg-green-500/10 border border-green-500/30 flex items-center justify-center flex-shrink-0">
          <Award className="w-8 h-8 text-green-400" />
        </div>
        <div className="flex-1">
          <h3 className="text-lg font-semibold text-green-300">Digital Certificate Available</h3>
          <p className="text-gray-400 text-sm mt-1">
            Your content scored above 90%! You can generate an official Human-Verified certificate.
          </p>
        </div>
        <button
          onClick={generateCertificate}
          disabled={generating}
          className="px-6 py-3 bg-gradient-to-r from-green-600 to-green-700 text-white font-medium rounded-xl hover:shadow-lg hover:shadow-green-500/25 transition-all disabled:opacity-50 flex items-center gap-2 w-full sm:w-auto justify-center"
        >
          {generating ? (
            <>
              <Loader2 className="w-5 h-5 animate-spin" />
              Generating...
            </>
          ) : (
            <>
              <Download className="w-5 h-5" />
              Download Certificate
            </>
          )}
        </button>
      </div>

      {certificateId && (
        <div className="mt-4 p-4 bg-black/50 rounded-lg border border-purple-900/30">
          <p className="text-gray-400 text-sm">
            Certificate ID: <span className="text-green-400 font-mono">{certificateId}</span>
          </p>
          <p className="text-gray-500 text-xs mt-1 flex items-center gap-1 flex-wrap">
            Verification URL: 
            <a 
              href={`/verify/${certificateId}`} 
              className="text-purple-400 hover:text-purple-300 transition-colors inline-flex items-center gap-1"
            >
              {typeof window !== 'undefined' ? window.location.origin : ''}/verify/{certificateId}
              <ExternalLink className="w-3 h-3" />
            </a>
          </p>
        </div>
      )}
    </motion.div>
  )
}
