'use client'

import { useState } from 'react'
import { motion } from 'framer-motion'
import { jsPDF } from 'jspdf'
import QRCode from 'qrcode'

interface CertificateGeneratorProps {
  score: number
  content: string
  verificationId: string | null
  userId?: string
}

export default function CertificateGenerator({
  score,
  content,
  verificationId,
  userId,
}: CertificateGeneratorProps) {
  const [generating, setGenerating] = useState(false)
  const [certificateId, setCertificateId] = useState<string | null>(null)

  const generateCertificate = async () => {
    setGenerating(true)

    try {
      // First, create certificate record in database
      const response = await fetch('/api/certificate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          verificationId,
          score,
          content: content.substring(0, 200),
          userId,
        }),
      })

      const data = await response.json()
      
      if (data.error) {
        console.error('Certificate error:', data.error)
        return
      }

      setCertificateId(data.certificateId)

      // Generate QR code
      const verifyUrl = `${window.location.origin}/verify/${data.certificateId}`
      const qrDataUrl = await QRCode.toDataURL(verifyUrl, {
        width: 150,
        margin: 1,
        color: {
          dark: '#1e293b',
          light: '#f8fafc',
        },
      })

      // Create PDF
      const pdf = new jsPDF({
        orientation: 'landscape',
        unit: 'mm',
        format: 'a4',
      })

      const width = pdf.internal.pageSize.getWidth()
      const height = pdf.internal.pageSize.getHeight()

      // Background
      pdf.setFillColor(15, 23, 42)
      pdf.rect(0, 0, width, height, 'F')

      // Gold border
      pdf.setDrawColor(212, 175, 55)
      pdf.setLineWidth(2)
      pdf.rect(10, 10, width - 20, height - 20)

      // Inner border
      pdf.setDrawColor(139, 92, 246)
      pdf.setLineWidth(0.5)
      pdf.rect(15, 15, width - 30, height - 30)

      // Corner decorations
      const corners = [
        { x: 20, y: 20 },
        { x: width - 20, y: 20 },
        { x: 20, y: height - 20 },
        { x: width - 20, y: height - 20 },
      ]

      pdf.setFillColor(212, 175, 55)
      corners.forEach(({ x, y }) => {
        pdf.circle(x, y, 3, 'F')
      })

      // Title
      pdf.setTextColor(212, 175, 55)
      pdf.setFontSize(36)
      pdf.setFont('helvetica', 'bold')
      pdf.text('CERTIFICATE OF AUTHENTICITY', width / 2, 45, { align: 'center' })

      // Subtitle
      pdf.setTextColor(139, 92, 246)
      pdf.setFontSize(14)
      pdf.setFont('helvetica', 'normal')
      pdf.text('Human-Verified Hub | Forensic Linguistic Analysis', width / 2, 55, { align: 'center' })

      // Main text
      pdf.setTextColor(248, 250, 252)
      pdf.setFontSize(16)
      pdf.text('This certifies that the analyzed content has been verified as', width / 2, 75, { align: 'center' })

      // Human Original badge
      pdf.setFontSize(28)
      pdf.setTextColor(16, 185, 129)
      pdf.setFont('helvetica', 'bold')
      pdf.text('HUMAN ORIGINAL', width / 2, 95, { align: 'center' })

      // Score display
      pdf.setFontSize(48)
      pdf.setTextColor(16, 185, 129)
      pdf.text(`${score}%`, width / 2, 120, { align: 'center' })

      pdf.setFontSize(12)
      pdf.setTextColor(148, 163, 184)
      pdf.text('Human Authenticity Score', width / 2, 130, { align: 'center' })

      // Certificate details
      const detailsY = 145
      pdf.setFontSize(10)
      pdf.setTextColor(148, 163, 184)
      
      pdf.text(`Certificate ID: ${data.certificateId}`, 30, detailsY)
      pdf.text(`Issued: ${new Date().toLocaleDateString('en-US', { 
        year: 'numeric', 
        month: 'long', 
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit'
      })}`, 30, detailsY + 8)

      // Content preview
      pdf.setFontSize(9)
      pdf.text('Content Preview:', 30, detailsY + 20)
      const preview = content.substring(0, 150).replace(/\n/g, ' ') + '...'
      const splitPreview = pdf.splitTextToSize(preview, 150)
      pdf.text(splitPreview, 30, detailsY + 28)

      // Add QR code
      pdf.addImage(qrDataUrl, 'PNG', width - 55, detailsY - 10, 35, 35)
      pdf.setFontSize(8)
      pdf.text('Scan to verify', width - 38, detailsY + 28, { align: 'center' })

      // Seal
      pdf.setDrawColor(212, 175, 55)
      pdf.setLineWidth(1)
      pdf.circle(width / 2, height - 35, 15)
      pdf.setTextColor(212, 175, 55)
      pdf.setFontSize(8)
      pdf.text('VERIFIED', width / 2, height - 35, { align: 'center' })

      // Footer
      pdf.setTextColor(100, 116, 139)
      pdf.setFontSize(8)
      pdf.text('This certificate was generated by Human-Verified Hub using advanced AI detection algorithms.', width / 2, height - 15, { align: 'center' })
      pdf.text('Verify authenticity at: ' + verifyUrl, width / 2, height - 10, { align: 'center' })

      // Save PDF
      pdf.save(`human-verified-certificate-${data.certificateId}.pdf`)

    } catch (error) {
      console.error('Failed to generate certificate:', error)
    } finally {
      setGenerating(false)
    }
  }

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="bg-gradient-to-r from-emerald-500/10 to-violet-500/10 rounded-xl p-6 border border-emerald-500/30"
    >
      <div className="flex items-center gap-4">
        <div className="w-16 h-16 rounded-full bg-emerald-500/20 flex items-center justify-center">
          <span className="text-3xl">🏆</span>
        </div>
        <div className="flex-1">
          <h3 className="text-lg font-semibold text-emerald-300">Digital Certificate Available</h3>
          <p className="text-slate-400 text-sm mt-1">
            Your content scored above 90%! You can generate an official Human-Verified certificate.
          </p>
        </div>
        <button
          onClick={generateCertificate}
          disabled={generating}
          className="px-6 py-3 bg-gradient-to-r from-emerald-500 to-green-500 text-white font-medium rounded-xl hover:opacity-90 transition-all disabled:opacity-50 flex items-center gap-2"
        >
          {generating ? (
            <>
              <svg className="w-5 h-5 animate-spin" viewBox="0 0 24 24">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" fill="none" />
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
              </svg>
              Generating...
            </>
          ) : (
            <>
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
              Download Certificate
            </>
          )}
        </button>
      </div>

      {certificateId && (
        <div className="mt-4 p-4 bg-slate-900/50 rounded-lg">
          <p className="text-slate-400 text-sm">
            Certificate ID: <span className="text-emerald-400 font-mono">{certificateId}</span>
          </p>
          <p className="text-slate-500 text-xs mt-1">
            Verification URL: <a href={`/verify/${certificateId}`} className="text-violet-400 hover:underline">{window.location.origin}/verify/{certificateId}</a>
          </p>
        </div>
      )}
    </motion.div>
  )
}
