'use client'

import Link from 'next/link'
import { ArrowLeft, FileText } from 'lucide-react'
import { useLanguage } from '@/contexts/LanguageContext'

export default function TermsPage() {
  const { language, isRTL } = useLanguage()

  return (
    <div className="min-h-screen bg-[#0a0a0a]" dir={isRTL ? 'rtl' : 'ltr'}>
      {/* Header */}
      <header className="border-b border-purple-900/30 bg-black/50 backdrop-blur-sm sticky top-0 z-40">
        <div className="max-w-4xl mx-auto px-4 py-4 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2 text-gray-400 hover:text-purple-400 transition-colors">
            <ArrowLeft className="w-4 h-4" />
            <span className="text-sm">{language === 'ar' ? 'العودة' : 'Back'}</span>
          </Link>
          <div className="flex items-center gap-2">
            <FileText className="w-5 h-5 text-purple-400" />
            <span className="text-white font-semibold">Human Verified Hub</span>
          </div>
        </div>
      </header>

      {/* Content */}
      <main className="max-w-4xl mx-auto px-4 py-12">
        <div className="space-y-8">
          <div className="text-center mb-12">
            <h1 className="text-3xl md:text-4xl font-bold text-white mb-4">
              <span className="text-purple-400">Terms</span> of Service
            </h1>
            <p className="text-gray-400">Last updated: January 2026</p>
          </div>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-purple-400">1. Acceptance of Terms</h2>
            <p className="text-gray-300 leading-relaxed">
              By accessing or using Human Verified Hub ("Service") at humanverified.systems, you agree to be bound 
              by these Terms of Service. If you do not agree to these terms, please do not use our Service.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-purple-400">2. Description of Service</h2>
            <p className="text-gray-300 leading-relaxed">
              Human Verified Hub provides AI Text Detection and Plagiarism Checking services. Our platform uses 
              advanced AI technology to analyze text content and provide assessments regarding the likelihood 
              that content was generated by AI or written by humans. We also offer PDF certificates and reports 
              for verified content.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-purple-400">3. User Accounts</h2>
            <div className="text-gray-300 leading-relaxed space-y-3">
              <p>To access certain features, you may need to create an account. You are responsible for:</p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>Maintaining the confidentiality of your account credentials</li>
                <li>All activities that occur under your account</li>
                <li>Providing accurate and current account information</li>
                <li>Notifying us immediately of any unauthorized use</li>
              </ul>
            </div>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-purple-400">4. Acceptable Use</h2>
            <div className="text-gray-300 leading-relaxed">
              <p className="mb-3">You agree NOT to use the Service to:</p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>Submit illegal, harmful, or offensive content</li>
                <li>Infringe on intellectual property rights of others</li>
                <li>Attempt to circumvent security measures or access restrictions</li>
                <li>Overload or disrupt the Service through automated requests</li>
                <li>Use the Service for fraudulent purposes</li>
                <li>Resell or redistribute our services without authorization</li>
              </ul>
            </div>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-purple-400">5. Intellectual Property</h2>
            <div className="text-gray-300 leading-relaxed space-y-3">
              <p><strong className="text-white">Your Content:</strong> You retain ownership of any text you submit for analysis. By using our Service, you grant us a limited license to process your content solely for providing the analysis service.</p>
              <p><strong className="text-white">Our Service:</strong> The Human Verified Hub platform, including its algorithms, design, and branding, is our intellectual property protected by applicable laws.</p>
            </div>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-purple-400">6. Disclaimer of Accuracy</h2>
            <div className="p-4 bg-yellow-900/10 border border-yellow-500/30 rounded-xl">
              <p className="text-gray-300 leading-relaxed">
                <strong className="text-yellow-400">Important Disclaimer:</strong> AI detection technology is not 100% accurate. 
                Our analysis provides an assessment based on linguistic patterns and statistical analysis, but 
                <strong className="text-white"> false positives (human content flagged as AI) and false negatives (AI content 
                flagged as human) can occur</strong>. Human Verified Hub is not responsible for any consequences 
                resulting from decisions made based on our analysis results.
              </p>
            </div>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-purple-400">7. Limitation of Liability</h2>
            <div className="p-4 bg-red-900/10 border border-red-500/20 rounded-xl">
              <p className="text-gray-300 leading-relaxed">
                <strong className="text-red-400">No Liability for Consequences:</strong> Human Verified Hub shall NOT be held 
                responsible for any academic penalties, professional consequences, legal actions, reputational damage, 
                or any other negative outcomes that may result from the use of our service or reliance on our analysis results. 
                Users acknowledge that AI detection is inherently probabilistic and should be used as one factor among 
                many in making decisions about content authenticity.
              </p>
            </div>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-purple-400">8. Certificates and Reports</h2>
            <p className="text-gray-300 leading-relaxed">
              Certificates and PDF reports generated by our Service represent our analysis at a specific point in time. 
              They are not legal documents and should not be treated as definitive proof of content authenticity. 
              The certificate indicates that, based on our analysis, the content met our criteria for likely 
              human authorship at the time of analysis.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-purple-400">9. Service Availability</h2>
            <p className="text-gray-300 leading-relaxed">
              We strive to maintain high availability but do not guarantee uninterrupted access to the Service. 
              We may modify, suspend, or discontinue any aspect of the Service at any time without prior notice. 
              We are not liable for any service interruptions or data loss.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-purple-400">10. Pricing and Payments</h2>
            <p className="text-gray-300 leading-relaxed">
              During our beta period, premium features are available free of charge. When paid plans are introduced, 
              pricing and billing terms will be clearly communicated. We reserve the right to modify pricing with 
              reasonable advance notice to existing users.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-purple-400">11. Termination</h2>
            <p className="text-gray-300 leading-relaxed">
              We may terminate or suspend your access to the Service immediately, without prior notice, for any 
              breach of these Terms. Upon termination, your right to use the Service will cease immediately. 
              You may also delete your account at any time.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-purple-400">12. Changes to Terms</h2>
            <p className="text-gray-300 leading-relaxed">
              We reserve the right to modify these Terms at any time. We will provide notice of significant changes 
              by updating the "Last updated" date. Your continued use of the Service after changes constitutes 
              acceptance of the modified Terms.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-purple-400">13. Governing Law</h2>
            <p className="text-gray-300 leading-relaxed">
              These Terms shall be governed by and construed in accordance with applicable laws, without regard 
              to conflict of law principles. Any disputes arising from these Terms or the Service shall be 
              resolved through appropriate legal channels.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-purple-400">14. Contact Information</h2>
            <p className="text-gray-300 leading-relaxed">
              For questions about these Terms of Service, please contact us:
            </p>
            <div className="p-4 bg-black/50 border border-purple-900/30 rounded-xl">
              <p className="text-white font-semibold">Human Verified Hub</p>
              <p className="text-gray-400">Email: <a href="mailto:contact@humanverified.systems" className="text-purple-400 hover:underline">contact@humanverified.systems</a></p>
              <p className="text-gray-400">Website: <a href="https://humanverified.systems" className="text-purple-400 hover:underline">humanverified.systems</a></p>
            </div>
          </section>

          {/* Summary Box */}
          <div className="p-6 bg-purple-900/10 border border-purple-500/20 rounded-xl mt-12">
            <h3 className="text-lg font-semibold text-purple-400 mb-4">Summary of Key Points</h3>
            <ul className="text-gray-300 space-y-2 text-sm">
              <li>• AI detection is not 100% accurate - use results as guidance, not absolute truth</li>
              <li>• We process your text for analysis but do not claim ownership of your content</li>
              <li>• We are not responsible for any consequences from decisions based on our results</li>
              <li>• Certificates represent our analysis at a point in time, not definitive proof</li>
              <li>• You retain all rights to content you submit for analysis</li>
            </ul>
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-purple-900/30 mt-16">
        <div className="max-w-4xl mx-auto px-4 py-8 text-center">
          <p className="text-gray-500 text-sm">© 2026 Human Verified Hub. All rights reserved.</p>
          <div className="flex justify-center gap-6 mt-4 text-sm">
            <Link href="/privacy" className="text-gray-400 hover:text-purple-400 transition-colors">Privacy Policy</Link>
            <Link href="/" className="text-gray-400 hover:text-purple-400 transition-colors">Home</Link>
          </div>
        </div>
      </footer>
    </div>
  )
}
