import { NextResponse } from "next/server";
import { createClient } from '@supabase/supabase-js';
import { checkUsageBeforeAction, incrementUsageAfterSuccess, UsageStatus } from '@/lib/freemium';

// ============================================================================
// CONFIGURATION - STABILITY FIRST
// ============================================================================

// API Key from environment variable (Vercel config)
const GEMINI_API_KEY = process.env.GEMINI_API_KEY || "";

// MANDATORY: gemini-1.5-flash as primary for cost efficiency
// Using same proven model pattern as Text Analysis API
const VISION_MODELS = [
  'gemini-1.5-flash',      // Primary - cost efficient, proven working
  'gemini-flash-latest',   // Fallback 1 - confirmed working in text analysis
  'gemini-1.5-pro'         // Fallback 2 - higher quality if flash fails
];

// Low temperature (0.2) for forensic-level precision - same approach as Text Analysis
const GENERATION_CONFIG = {
  temperature: 0.2,
  maxOutputTokens: 4096,
  topP: 0.8,
  topK: 40
};

// ============================================================================
// LOGGING UTILITIES
// ============================================================================

function logStep(step: string, details?: Record<string, unknown>) {
  const timestamp = new Date().toISOString();
  console.log(`[${timestamp}] [IMAGE-ANALYZE] ${step}`, details ? JSON.stringify(details) : '');
}

function logError(step: string, error: unknown) {
  const timestamp = new Date().toISOString();
  console.error(`[${timestamp}] [IMAGE-ANALYZE ERROR] ${step}:`, error);
}

// ============================================================================
// HIGH-PRECISION SYSTEM PROMPT - Forensic-Level AI Image Detection
// Designed to force gemini-1.5-flash to behave with maximum accuracy
// ============================================================================

const SYSTEM_PROMPT = `You are SENTINEL-IMAGE V5.0, an expert forensic image analyst specialized in AI-generated image detection. You must be EXTREMELY precise and methodical.

## YOUR MISSION
Analyze the provided image to determine if it was generated by AI or is an authentic photograph. Your analysis must be evidence-based with specific observations.

## DETECTION METHODOLOGY (Apply ALL relevant checks)

### 1. ANATOMICAL ANALYSIS (For images with people)
- **Hands**: Count fingers precisely (AI often generates 4, 6, or malformed fingers)
- **Eyes**: Check iris patterns, reflection consistency, pupil alignment
- **Teeth**: Look for uniform size anomalies, impossible dental structures
- **Ears**: Verify natural asymmetry, lobe attachment consistency
- **Skin**: Detect "waxy" or "plastic" textures, unnatural pore patterns

### 2. TEXTURE & SURFACE ANALYSIS
- **Hair**: Individual strand visibility vs. painted mass appearance
- **Fabric**: Pattern consistency, weave logic, fold physics
- **Backgrounds**: Edge warping, impossible architecture, repeating patterns
- **Text/Signs**: Gibberish letters, font inconsistencies, warped characters

### 3. PHYSICS & LIGHTING
- **Shadows**: Direction consistency across all objects
- **Reflections**: Surface accuracy, eye reflection matching environment
- **Perspective**: Vanishing point consistency, scale logic
- **Depth of Field**: Natural bokeh vs. artificial blur

### 4. AI FINGERPRINTS
- **Edge artifacts**: Halo effects, unnatural transitions
- **Color banding**: Gradient stepping issues
- **Repetitive patterns**: Tiling artifacts, clone stamps
- **Micro-artifacts**: Pixel-level noise inconsistencies

## SCORING GUIDELINES (0-100 AI Probability)
- **0-20%**: Definitely authentic (natural imperfections, consistent physics)
- **21-40%**: Likely authentic (minor artifacts could be compression)
- **41-60%**: Uncertain (mixed signals)
- **61-80%**: Likely AI (clear artifacts or anatomical issues)
- **81-100%**: Definitely AI (multiple critical anomalies)

## OUTPUT FORMAT (STRICT JSON ONLY)

{
  "aiProbability": <integer 0-100>,
  "verdict": "<Authentic Photo | Likely Authentic | Uncertain | Likely AI | AI Generated>",
  "confidenceLevel": "<high | medium | low>",
  "summary": "<2-3 sentence forensic summary with specific observations>",
  "likelyModel": "<DALL-E 3 | Midjourney | Stable Diffusion | Firefly | Flux | null>",
  "artifacts": [
    {
      "name": "<artifact name>",
      "category": "<anatomical | texture | physics | artifact>",
      "severity": "<critical | high | medium | low>",
      "location": "<specific location>",
      "description": "<detailed evidence>"
    }
  ],
  "analysisDetails": {
    "handAnalysis": "<findings or 'N/A'>",
    "eyeAnalysis": "<findings or 'N/A'>",
    "textureAnalysis": "<findings>",
    "lightingAnalysis": "<findings>",
    "backgroundAnalysis": "<findings>"
  },
  "recommendations": "<verification tips>"
}

CRITICAL RULES:
1. Return ONLY valid JSON - no markdown, no code blocks, no extra text
2. Be specific about what you observe - cite exact locations and evidence
3. If uncertain, say so - don't guess
4. Include at least 2-3 artifacts if AI probability > 40%`;

// ============================================================================
// JSON PARSING - Multiple strategies for robustness
// ============================================================================

function parseGeminiResponse(responseText: string): Record<string, unknown> | null {
  logStep('Parsing response', { length: responseText.length });
  
  // Strategy 1: Direct JSON parse
  try {
    return JSON.parse(responseText);
  } catch {
    logStep('Direct parse failed');
  }
  
  // Strategy 2: Clean markdown and parse
  let cleaned = responseText
    .replace(/```json\s*/gi, '')
    .replace(/```\s*/gi, '')
    .trim();
  
  try {
    return JSON.parse(cleaned);
  } catch {
    logStep('Cleaned parse failed');
  }
  
  // Strategy 3: Extract JSON object with regex
  const jsonMatch = cleaned.match(/\{[\s\S]*\}/);
  if (jsonMatch) {
    try {
      return JSON.parse(jsonMatch[0]);
    } catch {
      logStep('Regex extraction failed');
    }
  }
  
  // Strategy 4: Manual bracket matching
  const startIdx = cleaned.indexOf('{');
  if (startIdx !== -1) {
    let depth = 0;
    let endIdx = startIdx;
    for (let i = startIdx; i < cleaned.length; i++) {
      if (cleaned[i] === '{') depth++;
      if (cleaned[i] === '}') {
        depth--;
        if (depth === 0) {
          endIdx = i + 1;
          break;
        }
      }
    }
    try {
      return JSON.parse(cleaned.substring(startIdx, endIdx));
    } catch {
      logStep('Manual extraction failed');
    }
  }
  
  logError('All parsing strategies failed', { preview: responseText.substring(0, 300) });
  return null;
}

// ============================================================================
// GEMINI VISION API CALL - Following Text Analysis pattern
// ============================================================================

interface VisionAPIResult {
  text: string | null;
  error: string | null;
  modelUsed?: string;
}

async function callGeminiVisionAPI(
  prompt: string,
  imageBase64: string,
  mimeType: string,
  apiKey: string
): Promise<VisionAPIResult> {
  
  for (const model of VISION_MODELS) {
    try {
      logStep(`Trying model: ${model}`);
      
      const controller = new AbortController();
      const timeoutId = setTimeout(() => {
        logStep(`Timeout triggered for ${model}`);
        controller.abort();
      }, 45000); // 45s timeout - same as Text Analysis

      const requestBody = {
        contents: [{
          parts: [
            { text: prompt },
            { 
              inlineData: { 
                mimeType: mimeType,
                data: imageBase64
              }
            }
          ]
        }],
        generationConfig: GENERATION_CONFIG,
        safetySettings: [
          { category: "HARM_CATEGORY_HARASSMENT", threshold: "BLOCK_NONE" },
          { category: "HARM_CATEGORY_HATE_SPEECH", threshold: "BLOCK_NONE" },
          { category: "HARM_CATEGORY_SEXUALLY_EXPLICIT", threshold: "BLOCK_NONE" },
          { category: "HARM_CATEGORY_DANGEROUS_CONTENT", threshold: "BLOCK_NONE" }
        ]
      };

      const response = await fetch(
        `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`,
        {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(requestBody),
          signal: controller.signal,
        }
      );

      clearTimeout(timeoutId);
      logStep(`Response received`, { status: response.status, model });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        const errorMsg = errorData?.error?.message || `HTTP ${response.status}`;
        logError(`Model ${model} failed`, { status: response.status, message: errorMsg });
        continue; // Try next model
      }

      const data = await response.json();
      const textContent = data?.candidates?.[0]?.content?.parts?.[0]?.text;

      if (textContent) {
        logStep(`Success with ${model}`, { responseLength: textContent.length });
        return { text: textContent, error: null, modelUsed: model };
      }

      // Check for safety block
      const finishReason = data?.candidates?.[0]?.finishReason;
      if (finishReason === 'SAFETY') {
        logStep(`Safety block on ${model}`);
        continue;
      }

      logStep(`Empty response from ${model}`, { finishReason });
      
    } catch (error: unknown) {
      const err = error as Error;
      if (err.name === 'AbortError') {
        logError(`Timeout on ${model}`, '45 seconds exceeded');
      } else {
        logError(`Error on ${model}`, err.message);
      }
      continue; // Try next model
    }
  }

  return { text: null, error: 'All vision models failed' };
}

// ============================================================================
// AUTH & FREEMIUM
// ============================================================================

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || '';
const SUPABASE_ANON_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || '';

async function getUserFromRequest(req: Request): Promise<{ userId: string | null }> {
  const authHeader = req.headers.get('authorization');
  
  if (!authHeader || !authHeader.startsWith('Bearer ') || !SUPABASE_URL || !SUPABASE_ANON_KEY) {
    return { userId: null };
  }

  try {
    const token = authHeader.replace('Bearer ', '');
    const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
    const { data: { user }, error } = await supabase.auth.getUser(token);
    
    if (error || !user) {
      return { userId: null };
    }
    
    return { userId: user.id };
  } catch {
    return { userId: null };
  }
}

// ============================================================================
// MAIN API HANDLER
// ============================================================================

export async function POST(req: Request) {
  logStep('=== NEW IMAGE ANALYSIS REQUEST ===');
  
  // Validate API key from environment
  if (!GEMINI_API_KEY) {
    logError('Configuration error', 'GEMINI_API_KEY not set in environment');
    return NextResponse.json({ 
      error: 'Service temporarily unavailable. Please try again later.',
      errorCode: 'API_CONFIG_ERROR'
    }, { status: 503 });
  }
  logStep('API key validated', { keyLength: GEMINI_API_KEY.length });

  try {
    // STRICT GATING: Require authentication for all analysis requests
    const { userId } = await getUserFromRequest(req);
    
    // Guest users must sign in to use the analysis API
    if (!userId) {
      logStep('Guest user blocked - authentication required');
      return NextResponse.json({
        error: 'Please sign in to analyze images. Create a free account to get 2 daily analyses.',
        errorCode: 'AUTH_REQUIRED',
        requireAuth: true
      }, { status: 401 });
    }
    
    // Check freemium limits BEFORE processing (no increment yet)
    const usageStatus = await checkUsageBeforeAction(userId);
    
    // Pro users have UNLIMITED access - skip all limit checks
    if (usageStatus.isPro) {
      logStep('Pro user - UNLIMITED ACCESS', { userId });
    } else {
      // STRICT ENFORCEMENT: Block free users if limit reached (return 403 Forbidden)
      if (!usageStatus.canUse) {
        logStep('Usage limit reached - BLOCKING REQUEST', { userId, usageStatus });
        return NextResponse.json({
          error: "You've used your 2 free daily analyses. Upgrade to Pro for unlimited access.",
          errorCode: 'USAGE_LIMIT_REACHED',
          usageStatus: {
            remaining: usageStatus.remaining,
            limit: usageStatus.limit,
            isPro: usageStatus.isPro,
            message: usageStatus.message
          },
          upgradeUrl: '/pricing'
        }, { status: 403 });
      }
    }
    
    logStep('Usage check passed', { 
      userId, 
      remaining: usageStatus.remaining, 
      isPro: usageStatus.isPro 
    });
    
    // Store for later use
    const currentUserId = userId;
    const isProUser = usageStatus.isPro;

    const body = await req.json();
    const { image, language = 'en' } = body;
    
    logStep('Request received', { 
      hasImage: !!image, 
      imageType: typeof image,
      language 
    });

    // Validate image presence
    if (!image || typeof image !== 'string') {
      return NextResponse.json({ 
        error: language === 'ar' ? 'لم يتم توفير صورة' : 'No image provided',
        errorCode: 'NO_IMAGE'
      }, { status: 400 });
    }

    // Parse base64 data URI
    let base64Data: string;
    let mimeType = 'image/jpeg';
    
    if (image.startsWith('data:')) {
      const match = image.match(/^data:([^;]+);base64,(.+)$/);
      if (!match) {
        return NextResponse.json({ 
          error: language === 'ar' ? 'صيغة صورة غير صالحة' : 'Invalid image format',
          errorCode: 'INVALID_FORMAT'
        }, { status: 400 });
      }
      mimeType = match[1];
      base64Data = match[2];
    } else {
      base64Data = image;
    }

    // Validate MIME type
    const validTypes = ['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/heic', 'image/heif'];
    if (!validTypes.includes(mimeType)) {
      return NextResponse.json({ 
        error: language === 'ar' ? 'صيغة صورة غير مدعومة' : `Unsupported format: ${mimeType}`,
        errorCode: 'UNSUPPORTED_FORMAT'
      }, { status: 400 });
    }

    // Validate size (base64 is ~33% larger than binary)
    const estimatedBytes = (base64Data.length * 3) / 4;
    const maxBytes = 15 * 1024 * 1024;
    
    if (estimatedBytes > maxBytes) {
      return NextResponse.json({ 
        error: language === 'ar' ? 'الصورة كبيرة جداً (الحد الأقصى 15 ميجابايت)' : 'Image too large (max 15MB)',
        errorCode: 'FILE_TOO_LARGE'
      }, { status: 400 });
    }

    logStep('Image validated', { 
      mimeType, 
      sizeMB: (estimatedBytes / 1024 / 1024).toFixed(2) 
    });

    // Build prompt with language hint
    const langHint = language === 'ar' 
      ? '\n\nIMPORTANT: Output all text fields (summary, descriptions, recommendations) in Arabic.'
      : '';
    
    const prompt = `${SYSTEM_PROMPT}${langHint}\n\nAnalyze this image for AI generation indicators. Be thorough and specific:`;
    
    // Call Gemini Vision API
    const apiResult = await callGeminiVisionAPI(prompt, base64Data, mimeType, GEMINI_API_KEY);

    if (!apiResult.text) {
      logError('All API calls failed', apiResult.error);
      return NextResponse.json({ 
        error: language === 'ar' 
          ? 'فشل تحليل الصورة. يرجى المحاولة مرة أخرى.' 
          : 'Image analysis failed. Please try again.',
        errorCode: 'ANALYSIS_FAILED'
      }, { status: 500 });
    }

    // Parse response
    let result = parseGeminiResponse(apiResult.text);
    
    // Fallback if parsing fails
    if (!result) {
      logStep('Parse failed, creating fallback result');
      const text = apiResult.text.toLowerCase();
      const hasAI = text.includes('ai generated') || text.includes('artificial') || text.includes('likely ai');
      
      result = {
        aiProbability: hasAI ? 65 : 35,
        verdict: hasAI ? 'Likely AI' : 'Uncertain',
        confidenceLevel: 'low',
        summary: 'Analysis completed but response format was unexpected.',
        likelyModel: null,
        artifacts: [],
        analysisDetails: {
          handAnalysis: 'N/A',
          eyeAnalysis: 'N/A',
          textureAnalysis: 'Unable to parse detailed analysis',
          lightingAnalysis: 'Unable to parse detailed analysis',
          backgroundAnalysis: 'Unable to parse detailed analysis'
        },
        recommendations: 'Try uploading a different image or try again.'
      };
    }

    // Normalize result
    const aiProb = Math.max(0, Math.min(100, Math.round(Number(result.aiProbability) || 50)));
    
    // Determine verdict based on probability if missing
    let verdict = result.verdict as string;
    if (!verdict || typeof verdict !== 'string') {
      if (aiProb >= 81) verdict = 'AI Generated';
      else if (aiProb >= 61) verdict = 'Likely AI';
      else if (aiProb >= 41) verdict = 'Uncertain';
      else if (aiProb >= 21) verdict = 'Likely Authentic';
      else verdict = 'Authentic Photo';
    }

    const finalResult = {
      aiProbability: aiProb,
      verdict,
      confidenceLevel: ['high', 'medium', 'low'].includes(result.confidenceLevel as string) 
        ? result.confidenceLevel 
        : 'medium',
      summary: result.summary || 'Analysis completed.',
      likelyModel: result.likelyModel || null,
      artifacts: Array.isArray(result.artifacts) ? result.artifacts : [],
      analysisDetails: result.analysisDetails || {},
      recommendations: result.recommendations || 'Use high-resolution original images for best results.',
      modelUsed: apiResult.modelUsed
    };

    // INCREMENT USAGE AFTER SUCCESSFUL ANALYSIS (only for free users)
    if (!isProUser) {
      const updatedUsage = await incrementUsageAfterSuccess(currentUserId);
      if (updatedUsage) {
        logStep('Usage incremented after success', {
          userId: currentUserId,
          usedToday: updatedUsage.usedToday,
          remaining: updatedUsage.remaining
        });
        // Include updated usage in response for UI update
        (finalResult as any).usageStatus = {
          remaining: updatedUsage.remaining,
          usedToday: updatedUsage.usedToday,
          limit: updatedUsage.limit,
          isPro: updatedUsage.isPro
        };
      }
    } else {
      // Pro user - include unlimited status
      (finalResult as any).usageStatus = {
        remaining: -1,
        usedToday: 0,
        limit: -1,
        isPro: true
      };
    }

    logStep('=== ANALYSIS COMPLETE ===', { 
      aiProbability: finalResult.aiProbability, 
      verdict: finalResult.verdict,
      model: finalResult.modelUsed
    });
    
    return NextResponse.json(finalResult);

  } catch (error: unknown) {
    const err = error as Error;
    logError('Unhandled error', { message: err.message, stack: err.stack });
    return NextResponse.json({ 
      error: 'An unexpected error occurred. Please try again.',
      errorCode: 'INTERNAL_ERROR'
    }, { status: 500 });
  }
}

export const runtime = 'nodejs';
export const maxDuration = 60;
