'use client'

import { useState } from 'react'
import { motion } from 'framer-motion'
import { createClient } from '@/lib/supabase/client'
import { useRouter } from 'next/navigation'
import { User } from '@supabase/supabase-js'
import Logo from '@/components/Logo'
import VerificationForm from '@/components/VerificationForm'
import VerificationHistory from '@/components/VerificationHistory'

interface DashboardClientProps {
  user: User
}

export default function DashboardClient({ user }: DashboardClientProps) {
  const [refreshTrigger, setRefreshTrigger] = useState(0)
  const router = useRouter()
  const supabase = createClient()

  const handleSignOut = async () => {
    await supabase.auth.signOut()
    router.push('/login')
    router.refresh()
  }

  const handleNewVerification = () => {
    setRefreshTrigger((prev) => prev + 1)
  }

  return (
    <div className="min-h-screen relative overflow-hidden">
      {/* Animated background */}
      <div className="absolute inset-0 pointer-events-none">
        <motion.div
          className="absolute top-0 right-0 w-[600px] h-[600px] bg-accent-primary/5 rounded-full filter blur-[100px]"
          animate={{
            scale: [1, 1.2, 1],
            opacity: [0.3, 0.5, 0.3],
          }}
          transition={{
            duration: 12,
            repeat: Infinity,
            ease: 'easeInOut',
          }}
        />
        <motion.div
          className="absolute bottom-0 left-0 w-[500px] h-[500px] bg-accent-secondary/5 rounded-full filter blur-[100px]"
          animate={{
            scale: [1.2, 1, 1.2],
            opacity: [0.4, 0.6, 0.4],
          }}
          transition={{
            duration: 15,
            repeat: Infinity,
            ease: 'easeInOut',
          }}
        />
      </div>

      {/* Header */}
      <header className="relative z-10 border-b border-dark-700/50 bg-dark-950/50 backdrop-blur-xl">
        <div className="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">
          <Logo size="sm" />
          <div className="flex items-center gap-6">
            <span className="text-dark-400 text-sm hidden sm:block">
              {user.email}
            </span>
            <motion.button
              onClick={handleSignOut}
              className="px-4 py-2 text-sm text-dark-400 hover:text-white border border-dark-600/50 hover:border-red-500/50 rounded-lg transition-all"
              whileHover={{ scale: 1.02 }}
              whileTap={{ scale: 0.98 }}
            >
              Sign Out
            </motion.button>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="relative z-10 max-w-7xl mx-auto px-6 py-12">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="mb-12"
        >
          <h1 className="text-3xl md:text-4xl font-bold text-white mb-4">
            Content <span className="text-gradient">Verification</span>
          </h1>
          <p className="text-dark-400 text-lg">
            Analyze any text to determine if it was written by a human or generated by AI.
          </p>
        </motion.div>

        <div className="grid lg:grid-cols-3 gap-8">
          {/* Main Form */}
          <motion.div
            className="lg:col-span-2"
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.2 }}
          >
            <div className="glass-card p-6 md:p-8">
              <h2 className="text-xl font-semibold text-white mb-6 flex items-center gap-2">
                <span className="text-accent-primary">🔬</span>
                New Analysis
              </h2>
              <VerificationForm userId={user.id} onNewVerification={handleNewVerification} />
            </div>
          </motion.div>

          {/* Sidebar */}
          <motion.div
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.3 }}
            className="space-y-6"
          >
            {/* Quick Stats */}
            <div className="glass-card p-6">
              <h3 className="text-lg font-semibold text-white mb-4 flex items-center gap-2">
                <span className="text-accent-primary">📊</span>
                Quick Tips
              </h3>
              <ul className="space-y-3 text-dark-400 text-sm">
                <li className="flex items-start gap-2">
                  <span className="text-accent-primary mt-0.5">•</span>
                  <span>Provide at least 50 characters for accurate analysis</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-accent-primary mt-0.5">•</span>
                  <span>Longer texts yield more reliable results</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-accent-primary mt-0.5">•</span>
                  <span>Check multiple paragraphs for best accuracy</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-accent-primary mt-0.5">•</span>
                  <span>Results are saved automatically to your history</span>
                </li>
              </ul>
            </div>

            {/* History */}
            <VerificationHistory userId={user.id} refreshTrigger={refreshTrigger} />
          </motion.div>
        </div>
      </main>
    </div>
  )
}
